import { AssessmentInput, Eligibility, EligibilityRule, RuleState } from '../types/assessment';
export const eligibilityLabel: Record<Eligibility, string> = { likely_compatible: 'Likely compatible', needs_review: 'Needs review', incompatible_selected_route: 'Potential route issue', outside_mvp: 'Not assessed by this MVP' };
export function calculateEligibility(i: AssessmentInput): { status: Eligibility; rules: EligibilityRule[] } {
  const outside = !['Dairy', 'Piggery', '', 'Unsure'].includes(i.farmType) || (i.proposedProject !== '' && i.proposedProject !== 'Capture and flare methane');
  const routeUnknown = !['Dairy', 'Piggery'].includes(i.farmType) || !i.proposedProject || i.proposedProject === 'Other / unsure' || ['', 'Unsure', 'Other'].includes(i.wasteStream) || ['', 'Unsure', 'Other'].includes(i.manureSystem) || i.baselineAnaerobic === 'unknown';
  const routeBarrier = i.baselineAnaerobic === 'no' || i.wasteStream === 'Solid manure' || ['Aerobic pond', 'Dry manure storage', 'Composting'].includes(i.manureSystem);
  const rules: EligibilityRule[] = [];
  const add = (id: string, state: RuleState, title: string, explanation: string, inputReferences: (keyof AssessmentInput)[], nextAction: string) => rules.push({ id, state, title, explanation, inputReferences, nextAction });
  add('EL01_ROUTE_FIT', outside ? 'not_applicable' : routeBarrier ? 'barrier' : routeUnknown ? 'unresolved' : 'satisfied', 'Farm and baseline route', outside ? 'This pathway needs specialist assessment; it is not a legal rejection.' : routeBarrier ? 'The selected flare route assumes liquid animal effluent that would otherwise enter an anaerobic pond.' : routeUnknown ? 'Confirm the waste stream and anaerobic pond baseline.' : 'A dairy/piggery liquid-effluent pathway is identified.', ['farmType','wasteStream','manureSystem','baselineAnaerobic','proposedProject'], 'Confirm the eligible waste pathway and document the baseline pond.');
  add('EL02_BASELINE_EVIDENCE', ['Historical records available','New / expanded facility evidence available'].includes(i.baselineEvidence) && !['Covered lagoon','Anaerobic digester'].includes(i.manureSystem) ? 'satisfied' : 'unresolved', 'Baseline evidence', 'Historical or new-facility records and existing capture infrastructure need method-specific review.', ['baselineEvidence','manureSystem'], 'Collect baseline waste-management evidence.');
  add('EL03_NEWNESS', ['Just exploring','Planning / obtaining quotes'].includes(i.projectStage) ? 'satisfied' : 'unresolved', 'Project timing', ['Just exploring','Planning / obtaining quotes'].includes(i.projectStage) ? 'Planning only: provisional positive screening, subject to confirmation.' : `Project timing requires review${i.implementationDate ? ` (activity date ${i.implementationDate})` : ''}. Implementation does not establish a permanent legal rejection.`, ['projectStage','implementationDate'], 'Confirm whether project commencement affects the ACCU newness requirement.');
  add('EL04_ADDITIONALITY', i.legallyRequired === 'no' && i.normalBusinessPractice === 'no' ? 'satisfied' : 'unresolved', 'Additionality', 'Legal obligations and normal business practice require a method-specific additionality review.', ['legallyRequired','normalBusinessPractice'], 'Review legal obligations and business-as-usual activity with an adviser.');
  add('EL05_RIGHTS', i.siteControl === 'no' || i.accuRights === 'no' ? 'barrier' : i.siteControl === 'yes' && i.accuRights === 'yes' ? 'satisfied' : 'unresolved', 'Project legal rights', 'Site permission and rights to receive ACCUs are separate; property ownership does not prove both.', ['siteControl','accuRights'], 'Confirm project legal rights before applying.');
  add('EL06_FUNDING_OVERLAP', i.governmentFunding === 'no' ? 'satisfied' : 'unresolved', 'Funding interaction', i.governmentFunding === 'yes' ? 'Funding interaction requires review. Funding does not automatically prevent participation.' : i.governmentFunding === 'unknown' ? 'Confirm any grants or environmental certificates.' : 'No overlap reported; confirm before applying.', ['governmentFunding','fundingProgram','fundingAmount','fundingActivity'], 'Review government funding and environmental-certificate interactions.');
  add('EL07_TECHNICAL_ROUTE', outside ? 'not_applicable' : i.proposedProject === 'Capture and flare methane' && ['Open flare','Enclosed flare'].includes(i.flareType) ? 'satisfied' : 'unresolved', 'Destruction device route', 'This MVP calculates capture with an open or enclosed flare. Gas and operating data are preparation inputs, not a legal eligibility decision.', ['proposedProject','flareType'], 'Confirm the flare type and destruction-device requirements.');
  const status: Eligibility = outside ? 'outside_mvp' : rules.some(r => r.state === 'barrier') ? 'incompatible_selected_route' : rules.some(r => r.state === 'unresolved') ? 'needs_review' : 'likely_compatible';
  return { status, rules };
}
