import { expect, it } from 'vitest';
import { assessmentSchema, farmSchema, projectSchema, technicalSchema, financeSchema, priceSchema } from '../src/lib/validation';
import { demoInput } from '../src/lib/demo';
it('accepts the complete demo', () => expect(assessmentSchema.safeParse(demoInput).success).toBe(true));
it('allows unknown animals, gas, operation, emissions and costs', () => expect(assessmentSchema.safeParse({ ...demoInput, animalCount: undefined, biogasVolumeM3: undefined, flareOperationFraction: undefined, projectEmissionsTCO2e: undefined, implementationCost: undefined }).success).toBe(true));
it.each([-1,1.5,NaN])('rejects invalid animal count %s', animalCount => expect(farmSchema.safeParse({ ...demoInput,animalCount }).success).toBe(false));
it.each([-1,Infinity,NaN])('rejects invalid gas %s', biogasVolumeM3 => expect(technicalSchema.safeParse({ ...demoInput,biogasVolumeM3 }).success).toBe(false));
it('allows explicit zero gas and zero cost', () => expect(assessmentSchema.safeParse({ ...demoInput,biogasVolumeM3:0,implementationCost:0 }).success).toBe(true));
it('bounds fractions and rejects boolean unknown answers', () => { expect(technicalSchema.safeParse({ ...demoInput,methaneFraction:1.01 }).success).toBe(false); expect(technicalSchema.safeParse({ ...demoInput,qaPlan:false }).success).toBe(false); });
it('checks real activity dates and financial price ordering', () => { expect(projectSchema.safeParse({ ...demoInput,implementationDate:'2026-02-30' }).success).toBe(false); expect(financeSchema.safeParse({ ...demoInput,lowAccuPrice:99 }).success).toBe(false); });
it.each([-1,Infinity,NaN,100001])('rejects invalid price %s', value => expect(priceSchema.safeParse(value).success).toBe(false));
