import React, { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Body, Button, Card, DisclaimerCard, EmptyState, ErrorNotice, Heading, Icon, Screen, styles } from '../../components/ui';
import { ResultsView } from '../../components/ResultsView';
import { errorMessage, useApp } from '../../state/AppProvider';
import { View } from 'react-native';
export default function Details() {
  const { id } = useLocalSearchParams<{ id: string }>(), app = useApp(), record = app.records.find(row => row.id === id);
  const [confirm, setConfirm] = useState(false), [error, setError] = useState('');
  if (!record) return <Screen title="Assessment details" back><ErrorNotice message={app.listError} /><EmptyState title="Assessment unavailable" text="Refresh saved assessments to load this record, or return to your list." action="Refresh" onPress={() => void app.refresh()} /><Button title="Saved assessments" secondary onPress={() => router.replace('/(tabs)/saved')} /></Screen>;
  const edit = (duplicate = false) => { app.edit(record, duplicate); router.push('/assessment/farm-profile'); };
  const remove = async () => { try { await app.remove(record.id); router.replace('/(tabs)/saved'); } catch (e) { setError(errorMessage(e)); } };
  return <Screen title="Assessment details" back><Card><Heading small>{record.sample ? 'Sample · ' : ''}{record.input.farmType} farm</Heading><Body>{record.input.animalCount} animals · {record.input.state}</Body><Body muted>{record.input.manureSystem}</Body><Body muted>{record.input.proposedProject}</Body><Body muted style={{ fontSize: 12 }}>Saved {new Date(record.updatedAt).toLocaleString('en-AU')} · Assumptions {record.assumptions.version}</Body></Card>{record.legacySnapshot != null && <Card pale><Body>Original legacy snapshot is preserved. This view uses the new screening engine; historical herd-count estimates are not reused as current abatement.</Body></Card>}<ResultsView input={record.input} result={record.result} assumptions={record.assumptions} /><Heading small>Your next steps</Heading>{record.result.actionPlan.filter(task => task.status !== 'complete').map(task => <Card key={task.id}><View style={styles.row}><Icon name="sprout" /><Body style={{ flex: 1 }}>{task.title}</Body></View></Card>)}<Button title="Edit assessment" icon="pencil-outline" onPress={() => edit()} /><Button title="Duplicate as a new draft" secondary icon="content-copy" onPress={() => edit(true)} /><ErrorNotice message={error} />{confirm ? <Card><Heading small>Delete this assessment?</Heading><Body>This removes the saved record. You cannot undo this action.</Body><Button title="Delete permanently" destructive loading={app.busy} onPress={() => void remove()} /><Button title="Keep assessment" secondary onPress={() => setConfirm(false)} /></Card> : <Button title="Delete assessment" secondary icon="trash-can-outline" onPress={() => setConfirm(true)} />}<DisclaimerCard /></Screen>;
}
