import React, { useState } from 'react';
import { router } from 'expo-router';
import { Body, Button, Card, EmptyState, ErrorNotice, Heading, Icon, Screen, StatusBadge, money, number, styles } from '../../components/ui';
import { useApp } from '../../state/AppProvider';
import { View } from 'react-native';
export default function Saved() {
  const app = useApp(), [searched, setSearched] = useState(false);
  return <Screen title="Saved assessments" subtitle="Your farm’s possibilities, in one place."><Button title={app.busy ? 'Refreshing…' : 'Refresh assessments'} secondary loading={app.busy} onPress={() => { setSearched(true); void app.refresh(); }} /><ErrorNotice message={app.listError} onRetry={() => void app.refresh()} />{!app.records.length ? <EmptyState title="A fresh start" text={searched && app.listError ? 'Your saved assessments could not be loaded. Retry when connected.' : 'Save an assessment to keep its estimates and action plan here.'} action="Check my farm" onPress={() => { app.startNew(); router.push('/assessment/farm-profile'); }} /> : app.records.map(record => <Card key={record.id}><View style={styles.row}><Icon name={record.input.farmType === 'Dairy' ? 'cow' : 'pig-variant-outline'} size={30} /><View style={{ flex: 1 }}><Heading small>{record.input.farmType} · {record.input.state}</Heading><Body muted>{record.input.animalCount} animals{record.sample ? ' · Sample farm' : ''}</Body></View></View><StatusBadge status={record.result.eligibility} /><Body>{number(record.result.accus)} ACCUs/yr · {money(record.result.annualValue)}/yr</Body><Body muted>{record.result.readiness}% prepared · {new Date(record.updatedAt).toLocaleDateString('en-AU')}</Body><Button title="View details" secondary onPress={() => router.push(`/assessment-details/${record.id}`)} /></Card>)}<Body muted style={{ fontSize: 11 }}>All estimates are indicative. Saved results retain the assumptions used at the time.</Body></Screen>;
}
